name: sh-test
#     ^^^^^^^
# https://github.com/organization/repository/workflows/sh-test/badge.svg
#                                                      ^^^^^^^

on:
  push:
    # NO paths-ignore
  pull_request:
    # NO paths-ignore
  workflow_dispatch:

# NOTE: Cancel the previous run of the same workflow if it's still running
concurrency:
  group: ${{ github.workflow }}-${{ github.base_ref }}-${{ github.head_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  WORKDIR: .

defaults:
  run:
    shell: bash

jobs:
  sh-test: # NOTE: for Branch protection rule `Status checks that are required.`
    runs-on: ubuntu-latest # ref. https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
      - uses: actions/checkout@v4
      - name: DEBUG
        run: |
          cat <<'DEBUG_DOC'
          == DEBUG =======================================================
          github.ref: ${{ github.ref }}
          github.event_name: ${{ github.event_name }}
          -- toJSON(github.event.inputs) ---------------------------------
          ${{ toJSON(github.event.inputs) }}
          -- toJSON(github) ----------------------------------------------
          ${{ toJSON(github) }}
          ================================================================
          DEBUG_DOC
        shell: bash
      - name: Run test.sh
        working-directory: ${{ env.WORKDIR }}
        run: |
          ${{ env.WORKDIR }}/test.sh
